name: Rust

on:
  push:
    paths:
      - '**.rs'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: "Cding into dir"
      run: "cd ./code/pibcolor"
      shell: pwsh
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
